export const CREATE_TODO = 'CREATE_TODO';
export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS';
export const CREATE_TODO_ERROR = 'CREATE_TODO_ERROR';

export const DELETE_TODO = 'CREATE_TODO';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_ERROR = 'DELETE_TODO_ERROR';

export const INIT_TODOS = 'INIT_TODO';
export const INIT_TODOS_ERROR = 'INIT_TODO_ERROR';
export const INIT_TODOS_SUCCESS = 'INIT_TODO_SUCCESS';

export const EDIT_TODO = 'EDIT_CONTACT';
export const EDIT_TODO_SUCCESS = 'EDIT_CONTACT_SUCCESS';
export const EDIT_TODO_ERROR = 'EDIT_CONTACT_ERROR';
